#line 2 "/home/andreas/KDE-work/4.0/build/kdevelop-pg/kdev-pg/kdev-pg-lexer.cc"

#line 4 "/home/andreas/KDE-work/4.0/build/kdevelop-pg/kdev-pg/kdev-pg-lexer.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[275] =
    {   0,
        1,    1,   67,   67,   28,   28,   43,   43,   46,   46,
       62,   62,   75,   73,   74,    1,   73,   74,    2,   74,
        2,   73,   74,   73,   74,   10,   73,   74,   73,   74,
        6,   73,   74,    7,   73,   74,   15,   73,   74,   14,
       73,   74,    8,   73,   74,   73,   74,   11,   73,   74,
        9,   71,   73,   74,   71,   73,   74,   12,   73,   74,
       73,   74,   13,   73,   74,   16,   73,   74,   17,   73,
       74,   70,   71,   73,   74,   39,   73,   74,   71,   73,
       74,   71,   73,   74,   18,   73,   74,   67,   74,   66,
       74,   66,   74,   68,   74,   38,   74,   28,   38,   74,

       29,   74,   29,   38,   74,   30,   38,   74,   37,   38,
       74,   38,   74,   38,   74,   38,   74,   43,   74,   40,
       74,   40,   74,   42,   74,   44,   74,   45,   74,   60,
       74,   46,   60,   74,   47,   74,   47,   60,   74,   50,
       60,   74,   60,   74,   58,   60,   74,   49,   60,   74,
       57,   60,   74,   59,   60,   74,   58,   60,   74,   58,
       60,   74,   58,   60,   74,   58,   60,   74,   58,   60,
       74,   62,   64,   74,   61,   74,   61,   64,   74,   63,
       64,   74,    1,    2,   72,    3,    5,   71,    4,   70,
       71,   65,   71,   71,   67,   66,   68,   68,   69,   28,

       29,   43,   40,   41,   46,   47,   48,   58,   49,   58,
       58,   58,   58,   58,   58,   62,   61,   72,    3,   71,
       71,   41,   48,   58,   58,   58,   58,   58,   58,   71,
       58,   58,   54,   58,   58,   58,   58,   21,   71,   58,
       58,   58,   55,   58,   58,   24,   31,   58,   51,   58,
       58,   58,   32,   58,   58,   58,   53,   58,   58,   56,
       58,   33,   52,   58,   26,   36,   19,   35,   34,   27,
       20,   22,   25,   23
    } ;

static yyconst flex_int16_t yy_accept[270] =
    {   0,
        1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   16,   19,   21,   24,   26,   29,
       31,   34,   37,   40,   43,   46,   48,   51,   55,   58,
       61,   63,   66,   69,   72,   76,   79,   82,   85,   88,
       90,   92,   94,   96,   98,  101,  103,  106,  109,  112,
      114,  116,  118,  120,  122,  124,  126,  128,  130,  132,
      135,  137,  140,  143,  145,  148,  151,  154,  157,  160,
      163,  166,  169,  172,  175,  177,  180,  183,  184,  185,
      185,  186,  186,  186,  186,  186,  186,  187,  188,  189,
      190,  192,  193,  194,  195,  196,  197,  198,  199,  200,

      201,  202,  202,  202,  202,  202,  203,  204,  204,  205,
      205,  206,  207,  208,  209,  210,  211,  212,  213,  214,
      215,  216,  217,  218,  218,  219,  219,  219,  219,  219,
      219,  220,  221,  222,  222,  222,  222,  222,  222,  222,
      222,  223,  223,  224,  225,  226,  227,  228,  229,  230,
      230,  230,  230,  230,  231,  231,  231,  231,  231,  231,
      231,  231,  232,  233,  235,  236,  237,  238,  238,  238,
      238,  238,  240,  240,  240,  240,  240,  240,  240,  240,
      241,  242,  243,  245,  246,  246,  246,  246,  247,  247,
      247,  247,  247,  247,  247,  247,  248,  249,  251,  252,

      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      254,  254,  255,  256,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  259,  260,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  263,  265,  265,
      266,  266,  266,  266,  266,  266,  266,  267,  267,  267,
      267,  268,  268,  269,  270,  270,  271,  271,  272,  273,
      274,  274,  274,  274,  274,  274,  274,  275,  275
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    7,    1,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,    1,
       20,   21,   22,   23,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       25,   26,   27,    1,   28,    1,   29,   30,   31,   32,

       33,   17,   34,   35,   36,   17,   37,   38,   39,   40,
       41,   42,   17,   43,   44,   45,   46,   47,   17,   48,
       49,   17,    1,   50,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[51] =
    {   0,
        1,    1,    2,    2,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    4,    5,    6,    1,
        1,    1,    1,    4,    3,    1,    3,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1
    } ;

static yyconst flex_int16_t yy_base[285] =
    {   0,
        0,    0,   48,   50,   67,  108,   52,   55,  150,    0,
       59,   69,  417,  418,  414,  418,  412,   59,  418,   41,
      418,  418,  418,  418,  418,   71,  418,    0,    0,  418,
      395,  418,  418,  418,   37,  395,  383,  368,  418,    0,
      418,  407,   69,  418,  407,  418,  405,  418,  418,  366,
      373,   47,    0,  418,  402,   89,  418,  418,  418,  402,
      418,  400,  418,  389,    0,  399,  418,  418,  357,  366,
      357,   56,  368,    0,  418,  393,  418,  393,  418,   95,
      418,   96,  346,  364,  363,  350,    0,  418,    0,  418,
       67,  418,  345,  340,    0,  418,   86,   87,  418,  386,

      418,  347,   75,   66,  356,    0,  418,   98,  418,  103,
      383,  418,    0,    0,  382,  349,  343,  349,  341,  342,
      335,    0,  418,  115,  118,  120,  335,  337,  332,  337,
        0,  342,  357,  327,  332,  324,  321,  322,  328,  121,
      122,  123,    0,  319,  334,  330,  320,  328,  324,  318,
      325,  313,  323,  320,  311,  308,  323,  308,  321,  316,
      312,  308,  313,    0,  304,  304,  314,  299,  297,  307,
      299,    0,   97,  295,  294,  290,  290,  303,  302,  299,
      288,  287,    0,  299,  283,  285,  283,  297,  293,  285,
      276,  292,  289,  286,  273,  418,  277,    0,  287,  277,

      286,  284,  281,  267,  269,  271,  277,  262,  261,  418,
      272,  259,  260,  269,  262,  269,  261,  253,  250,  266,
      250,  258,  252,  260,    0,  242,    0,  261,  256,  259,
      244,  253,  256,  243,  238,  230,  418,    0,  236,  418,
      217,  223,  207,  214,  201,  198,  418,  192,  188,  197,
      418,  108,  418,  418,  102,  418,  103,  418,  109,  418,
      101,  102,  105,  101,   99,   88,  418,  418,  200,  206,
      212,  218,  224,  114,  230,  236,  242,  248,   63,  254,
      259,  265,  271,  277
    } ;

static yyconst flex_int16_t yy_def[285] =
    {   0,
      268,    1,  269,  269,  270,  270,  271,  271,  268,    9,
      272,  272,  268,  268,  268,  268,  268,  273,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  274,  274,  268,
      268,  268,  268,  268,  274,  268,  274,  274,  268,  275,
      268,  268,  276,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  277,  268,  268,  278,  268,  268,  268,  268,
      268,  268,  268,  268,  279,  268,  268,  268,  279,  279,
      279,  279,  279,  280,  268,  268,  268,  268,  268,  273,
      268,  281,  268,  268,  268,  268,  282,  268,  274,  268,
      274,  268,  274,  274,  275,  268,  276,  276,  268,  268,

      268,  268,  268,  268,  268,  277,  268,  278,  268,  283,
      268,  268,  284,  279,  268,  279,  279,  279,  279,  279,
      279,  280,  268,  273,  273,  281,  268,  268,  268,  268,
      282,  274,  274,  268,  268,  268,  268,  268,  268,  278,
      278,  283,  284,  279,  279,  279,  279,  279,  279,  268,
      268,  268,  268,  274,  268,  268,  268,  268,  268,  268,
      268,  279,  279,  279,  279,  279,  279,  268,  268,  268,
      268,  274,  268,  268,  268,  268,  268,  268,  268,  279,
      279,  279,  279,  279,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  279,  279,  279,  279,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  279,  279,  279,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  279,  279,  279,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  279,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,    0,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268
    } ;

static yyconst flex_int16_t yy_nxt[469] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   14,   28,   29,   30,   31,   32,
       14,   33,   34,   35,   36,   14,   14,   35,   29,   29,
       37,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   38,   29,   29,   29,   29,   39,
       41,   42,   41,   42,   54,   55,   56,   54,   55,   56,
       91,   75,   76,   81,   91,   43,  114,   43,   45,   46,
       47,   75,   76,   83,   48,   49,   57,   77,   58,   57,
       84,   58,   85,   87,   82,   86,   98,   77,  119,  104,
       91,   88,  105,  109,   91,   99,  120,   50,   51,   81,

      125,  137,  109,  268,   98,  135,  138,  141,   52,   45,
       46,   47,  268,  268,  110,   48,   49,   89,  136,   81,
       82,  126,   81,  110,  125,  109,  109,  141,  142,  189,
      267,  266,  265,  264,  263,  262,  261,  190,   50,   51,
       82,  260,  259,   82,  258,  126,  110,  110,  142,   52,
       59,   60,   61,   62,   59,   63,   59,   59,   59,   59,
       59,   59,   64,   59,   59,   65,   65,   66,   67,   59,
       59,   59,   59,   65,   59,   59,   68,   65,   69,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   70,   71,
       65,   65,   65,   65,   72,   65,   73,   65,   65,   59,

       40,   40,   40,   40,   40,   40,   44,   44,   44,   44,
       44,   44,   53,   53,   53,   53,   53,   53,   74,   74,
       74,   74,   74,   74,   80,  257,   80,   80,   80,   80,
       95,  256,   95,   95,  255,   95,   97,  254,   97,   97,
       97,   97,  106,  253,  252,  106,  106,  106,  108,  251,
      108,  108,  108,  108,  122,  250,  122,  122,  122,  124,
      249,  124,  124,  124,  124,  131,  248,  131,  131,  131,
      131,  140,  247,  140,  140,  140,  140,  143,  246,  143,
      143,  143,  143,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,

      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  147,
      146,  145,  144,  115,  111,  139,  134,  100,  133,  132,
      130,  129,  128,  127,   78,  123,  121,  118,  117,  116,

      115,  113,  112,  111,  107,  103,  102,  101,  100,   96,
       94,   93,   92,   90,   79,   78,  268,   13,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268
    } ;

static yyconst flex_int16_t yy_chk[469] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    4,    4,    7,    7,    7,    8,    8,    8,
       35,   11,   11,   18,   35,    3,  279,    4,    5,    5,
        5,   12,   12,   20,    5,    5,    7,   11,    7,    8,
       20,    8,   20,   26,   18,   20,   43,   12,   72,   52,
       91,   26,   52,   56,   91,   43,   72,    5,    5,   80,

       82,  104,  108,   97,   98,  103,  104,  110,    5,    6,
        6,    6,   97,   98,   56,    6,    6,  274,  103,  124,
       80,   82,  125,  108,  126,  140,  141,  142,  110,  173,
      266,  265,  264,  263,  262,  261,  259,  173,    6,    6,
      124,  257,  255,  125,  252,  126,  140,  141,  142,    6,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

      269,  269,  269,  269,  269,  269,  270,  270,  270,  270,
      270,  270,  271,  271,  271,  271,  271,  271,  272,  272,
      272,  272,  272,  272,  273,  250,  273,  273,  273,  273,
      275,  249,  275,  275,  248,  275,  276,  246,  276,  276,
      276,  276,  277,  245,  244,  277,  277,  277,  278,  243,
      278,  278,  278,  278,  280,  242,  280,  280,  280,  281,
      241,  281,  281,  281,  281,  282,  239,  282,  282,  282,
      282,  283,  236,  283,  283,  283,  283,  284,  235,  284,
      284,  284,  284,  234,  233,  232,  231,  230,  229,  228,
      226,  224,  223,  222,  221,  220,  219,  218,  217,  216,

      215,  214,  213,  212,  211,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  197,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  171,  170,
      169,  168,  167,  166,  165,  163,  162,  161,  160,  159,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  145,  144,  139,  138,  137,  136,  135,
      134,  133,  132,  130,  129,  128,  127,  121,  120,  119,
      118,  117,  116,  115,  111,  105,  102,  100,   94,   93,
       86,   85,   84,   83,   78,   76,   73,   71,   70,   69,

       66,   64,   62,   60,   55,   51,   50,   47,   45,   42,
       38,   37,   36,   31,   17,   15,   13,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
#line 2 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
/* This file is part of kdev-pg
   Copyright (C) 2006 Jakob Petsovits <jpetso@gmx.at>

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License as published by the Free Software Foundation; either
   version 2 of the License, or (at your option) any later version.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301, USA.
*/

#include <iostream>
#include <cstdio>
#include "kdev-pg.h"
#include "kdev-pg-parser.hh"

int inp();
void append_linebuffer();
void newline();
void yyerror(char const *);

#define YY_INPUT(buf, result, max_size) \
  { \
    char c = inp(); \
    result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); \
  }

#define YY_USER_ACTION  append_linebuffer();

#define COPY_TO_YYLVAL(string, len) \
  yylval.str = (char*) calloc(yyleng+1, sizeof(char)); \
  strcpy(yylval.str, string); \
  yylval.str[len] = '\0';

namespace {
  enum rule_position_enum {
    rule_body,
    rule_footer,
  };
  rule_position_enum rule_position = rule_body;
  int open_brackets; // for rule arguments usage
}






#line 744 "/home/andreas/KDE-work/4.0/build/kdevelop-pg/kdev-pg/kdev-pg-lexer.cc"

#define INITIAL 0
#define CODE 1
#define PARSERCLASS 2
#define RULE_ARGUMENTS 3
#define RULE_PARAMETERS_HEADER 4
#define RULE_PARAMETERS_VARNAME 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 65 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"



#line 906 "/home/andreas/KDE-work/4.0/build/kdevelop-pg/kdev-pg/kdev-pg-lexer.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 269 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 418 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 68 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
/* skip */ ;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 69 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
newline();
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 70 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
/* line comments, skip */ ;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 72 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
rule_position = rule_body;   return ';';
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 73 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
rule_position = rule_footer; return T_ARROW;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 75 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return '(';
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 76 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return ')';
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 77 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return ',';
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 78 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return '0';
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 79 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return '#';
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 80 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return '.';
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 81 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return ':';
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 82 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return '=';
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 83 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return '+';
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 84 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return '*';
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 85 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return '?';
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 86 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return '@';
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 87 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return '|';
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 89 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_TRY_RECOVER;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 90 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_TRY_ROLLBACK;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 91 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_CATCH;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 93 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_EXPORT_MACRO;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 94 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_EXPORT_MACRO_HEADER;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 95 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_TOKEN_DECLARATION;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 96 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_TOKEN_STREAM_DECLARATION;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 97 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_NAMESPACE_DECLARATION;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 98 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
BEGIN(PARSERCLASS); return T_PARSERCLASS_DECLARATION;
	YY_BREAK

case 28:
YY_RULE_SETUP
#line 102 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
/* skip */ ;
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 103 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
newline();
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 104 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return '(';
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 105 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_PUBLIC;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 106 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_PRIVATE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 107 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_PROTECTED;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 108 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_DECLARATION;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 109 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_CONSTRUCTOR;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 110 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_DESTRUCTOR;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 111 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
BEGIN(INITIAL); return ')';
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 112 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
BEGIN(INITIAL); REJECT; /* everything else */
	YY_BREAK

case 39:
YY_RULE_SETUP
#line 116 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
{
    if (rule_position == rule_body) { /* use the arguments in a rule call */
      open_brackets = 0;
      BEGIN(RULE_ARGUMENTS);
    }
    else if (rule_position == rule_footer) { /* declare the arguments */
      BEGIN(RULE_PARAMETERS_HEADER); return '[';
    }
}
	YY_BREAK

case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 127 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
newline(); yymore();
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 128 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
yymore(); /* this and... */
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 129 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
yymore(); /* ...this prevent brackets inside strings to be counted */
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 130 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
yymore(); /* gather everything that's not a bracket, and append what comes next */
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 131 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
open_brackets++; yymore();
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 132 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
{
    open_brackets--;
    if (open_brackets < 0) {
      COPY_TO_YYLVAL(yytext,yyleng-1); /* cut off the trailing bracket */
      BEGIN(INITIAL);
      return T_RULE_ARGUMENTS;
    }
}
	YY_BREAK
case YY_STATE_EOF(RULE_ARGUMENTS):
#line 140 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
{
    BEGIN(INITIAL); // is not set automatically by yyrestart()
    std::cout << "Encountered end of file in an unclosed rule argument specification..." << std::endl;
    yyerror("");
    return 0;
}
	YY_BREAK


case 46:
YY_RULE_SETUP
#line 149 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
/* skip */ ;
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 150 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
newline();
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 151 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
/* line comments, skip */ ;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 152 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
BEGIN(RULE_PARAMETERS_VARNAME); return ':';
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 153 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return '#';
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 154 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_MEMBER;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 155 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_TEMPORARY;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 156 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_ARGUMENT;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 157 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_NODE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 158 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_TOKEN;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 159 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return T_VARIABLE;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 160 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
return ';';  /* only used for "token" types */
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 161 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
COPY_TO_YYLVAL(yytext,yyleng); return T_IDENTIFIER;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 162 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
BEGIN(INITIAL); return ']';
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 163 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
BEGIN(INITIAL); REJECT; /* everything else */
	YY_BREAK


case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 167 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
newline(); yymore();
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 168 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
yymore(); /* gather everything that's not a semicolon, and append what comes next */
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 169 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
{
    // strip trailing whitespace
    int length = yyleng-1; // and first, the trailing semicolon
    for (int i = length-1; i < 1; i--) {
      switch(yytext[i-1])
      {
        case ' ':
        case '\f':
        case '\t':
          continue;
        default:
          length = i;
          break;
      }
    }
    COPY_TO_YYLVAL(yytext,length);
    BEGIN(RULE_PARAMETERS_HEADER);
    return T_IDENTIFIER;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 188 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
BEGIN(INITIAL); REJECT; /* everything else */
	YY_BREAK

case 65:
YY_RULE_SETUP
#line 192 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
BEGIN(CODE);
	YY_BREAK

case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 194 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
newline(); yymore();
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 195 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
yymore(); /* gather everything that's not a colon, and append what comes next */
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 196 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
yymore(); /* also gather colons that are not followed by colons or newlines */
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 197 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
{
    COPY_TO_YYLVAL(yytext,yyleng-2); /* cut off the trailing stuff */
    BEGIN(INITIAL);
    return T_CODE;
}
	YY_BREAK
case YY_STATE_EOF(CODE):
#line 202 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
{
    BEGIN(INITIAL); // is not set automatically by yyrestart()
    std::cout << "Encountered end of file in an unclosed code segment..." << std::endl;
    yyerror("");
    return 0;
}
	YY_BREAK

case 70:
YY_RULE_SETUP
#line 211 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
COPY_TO_YYLVAL(yytext,yyleng); return T_TERMINAL;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 212 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
COPY_TO_YYLVAL(yytext,yyleng); return T_IDENTIFIER;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 215 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
{
   yytext++;                         /* start inside the quotes */
   COPY_TO_YYLVAL(yytext,yyleng-2);  /* cut off the trailing quote */
   return T_STRING;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 221 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
{
  std::cout << "Unexpected character: ``" << yytext[0] << "''" << std::endl;
  yyerror("");
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 227 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"
ECHO;
	YY_BREAK
#line 1450 "/home/andreas/KDE-work/4.0/build/kdevelop-pg/kdev-pg/kdev-pg-lexer.cc"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(PARSERCLASS):
			case YY_STATE_EOF(RULE_PARAMETERS_HEADER):
			case YY_STATE_EOF(RULE_PARAMETERS_VARNAME):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 269 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 269 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 268);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 227 "/home/andreas/KDE-work/4.0/kdevelop-pg/kdev-pg/kdev-pg-lexer.ll"



extern FILE *file;

int ch = 0;
int yy_line = 1, current_offset = 0;
bool end_of_line = false;
char yy_text_line[256 * 1024];

int inp()
{
  return ch = fgetc(file);
}

void newline()
{
  yy_line++;
  end_of_line = true;
}

/* initialize the line buffer */
void clear_linebuffer()
{
  yy_text_line[0] = '\0';
  current_offset = 0;
  end_of_line = false;
}

 /* add the current token to the current line */
void append_linebuffer()
{
  if (end_of_line == true)
    clear_linebuffer();

  current_offset = strlen(yy_text_line); /* start of current */
  strcpy(yy_text_line+current_offset, yytext); /* append current */
  /* strcpy is faster than strcat */
}

void yyerror(char const *)
{
  std::cerr << "** SYNTAX ERROR at line " << yy_line << " column " << current_offset << std::endl;

  char *current_end = yy_text_line + strlen(yy_text_line);
  char *p;

  /* get the rest of the line if we are not already at the end */
  if(!end_of_line)
    {
      p = current_end;
      int c = ch;

      while(c != '\n')
        {
          *p++ = c;
          c = inp();
        }

      *p++ = '\n';
      *p = 0;
    }

  /* yy_text_line[] now has the whole line, with the current token */
  /* at current_offset */

  /* print error message and current line */
  std::cerr << yy_text_line;

  /* print a ^ under the most recent token */
  for (int i = 0; i < current_offset; i++)
    std::cerr << " ";

  std::cout << "^" << std::endl; /* current_offset spaces, then ^ */

  exit(EXIT_FAILURE);
}

int yywrap() { return 1; }


