// THIS FILE IS GENERATED
// WARNING! All changes made in this file will be lost!

#include "rphp_visitor.h"

namespace rphp
  {

  visitor::parser_fun_t visitor::_S_parser_table[] = {
        reinterpret_cast<parser_fun_t>(&visitor::visit_additiveExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_additiveExpressionRest),
        reinterpret_cast<parser_fun_t>(&visitor::visit_arrayPairValue),
        reinterpret_cast<parser_fun_t>(&visitor::visit_assignmentExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_assignmentExpressionCheckIfVariable),
        reinterpret_cast<parser_fun_t>(&visitor::visit_assignmentExpressionEqual),
        reinterpret_cast<parser_fun_t>(&visitor::visit_assignmentList),
        reinterpret_cast<parser_fun_t>(&visitor::visit_assignmentListElement),
        reinterpret_cast<parser_fun_t>(&visitor::visit_baseVariable),
        reinterpret_cast<parser_fun_t>(&visitor::visit_baseVariableWithFunctionCalls),
        reinterpret_cast<parser_fun_t>(&visitor::visit_bitAndExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_bitOrExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_bitXorExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_booleanAndExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_booleanOrExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_caseList),
        reinterpret_cast<parser_fun_t>(&visitor::visit_case_item),
        reinterpret_cast<parser_fun_t>(&visitor::visit_catch_item),
        reinterpret_cast<parser_fun_t>(&visitor::visit_classConstantDeclaration),
        reinterpret_cast<parser_fun_t>(&visitor::visit_classDeclarationStatement),
        reinterpret_cast<parser_fun_t>(&visitor::visit_classNameReference),
        reinterpret_cast<parser_fun_t>(&visitor::visit_classStatement),
        reinterpret_cast<parser_fun_t>(&visitor::visit_classVariable),
        reinterpret_cast<parser_fun_t>(&visitor::visit_classVariableDeclaration),
        reinterpret_cast<parser_fun_t>(&visitor::visit_commonScalar),
        reinterpret_cast<parser_fun_t>(&visitor::visit_compoundVariable),
        reinterpret_cast<parser_fun_t>(&visitor::visit_compoundVariableWithSimpleIndirectReference),
        reinterpret_cast<parser_fun_t>(&visitor::visit_conditionalExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_ctorArguments),
        reinterpret_cast<parser_fun_t>(&visitor::visit_declareItem),
        reinterpret_cast<parser_fun_t>(&visitor::visit_declareStatement),
        reinterpret_cast<parser_fun_t>(&visitor::visit_dimListItem),
        reinterpret_cast<parser_fun_t>(&visitor::visit_dimOffset),
        reinterpret_cast<parser_fun_t>(&visitor::visit_dynamicClassNameReference),
        reinterpret_cast<parser_fun_t>(&visitor::visit_dynamicClassNameVariableProperties),
        reinterpret_cast<parser_fun_t>(&visitor::visit_dynamicClassNameVariableProperty),
        reinterpret_cast<parser_fun_t>(&visitor::visit_elseSingle),
        reinterpret_cast<parser_fun_t>(&visitor::visit_elseifList),
        reinterpret_cast<parser_fun_t>(&visitor::visit_elseifListItem),
        reinterpret_cast<parser_fun_t>(&visitor::visit_encaps),
        reinterpret_cast<parser_fun_t>(&visitor::visit_encapsList),
        reinterpret_cast<parser_fun_t>(&visitor::visit_encapsVar),
        reinterpret_cast<parser_fun_t>(&visitor::visit_encapsVarOffset),
        reinterpret_cast<parser_fun_t>(&visitor::visit_equalityExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_equalityExpressionRest),
        reinterpret_cast<parser_fun_t>(&visitor::visit_expr),
        reinterpret_cast<parser_fun_t>(&visitor::visit_forExpr),
        reinterpret_cast<parser_fun_t>(&visitor::visit_forStatement),
        reinterpret_cast<parser_fun_t>(&visitor::visit_foreachOptionalArg),
        reinterpret_cast<parser_fun_t>(&visitor::visit_foreachStatement),
        reinterpret_cast<parser_fun_t>(&visitor::visit_foreachVariable),
        reinterpret_cast<parser_fun_t>(&visitor::visit_functionCall),
        reinterpret_cast<parser_fun_t>(&visitor::visit_functionCallParameterList),
        reinterpret_cast<parser_fun_t>(&visitor::visit_functionCallParameterListElement),
        reinterpret_cast<parser_fun_t>(&visitor::visit_functionDeclarationStatement),
        reinterpret_cast<parser_fun_t>(&visitor::visit_globalVar),
        reinterpret_cast<parser_fun_t>(&visitor::visit_innerStatementList),
        reinterpret_cast<parser_fun_t>(&visitor::visit_logicalAndExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_logicalOrExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_logicalXorExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_memberModifier),
        reinterpret_cast<parser_fun_t>(&visitor::visit_methodBody),
        reinterpret_cast<parser_fun_t>(&visitor::visit_multiplicativeExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_multiplicativeExpression_rest),
        reinterpret_cast<parser_fun_t>(&visitor::visit_newElseSingle),
        reinterpret_cast<parser_fun_t>(&visitor::visit_newElseifList),
        reinterpret_cast<parser_fun_t>(&visitor::visit_newelseifListItem),
        reinterpret_cast<parser_fun_t>(&visitor::visit_objectDimList),
        reinterpret_cast<parser_fun_t>(&visitor::visit_objectProperty),
        reinterpret_cast<parser_fun_t>(&visitor::visit_parameter),
        reinterpret_cast<parser_fun_t>(&visitor::visit_parameterList),
        reinterpret_cast<parser_fun_t>(&visitor::visit_postprefixOperator),
        reinterpret_cast<parser_fun_t>(&visitor::visit_printExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_relationalExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_relationalExpressionRest),
        reinterpret_cast<parser_fun_t>(&visitor::visit_scalar),
        reinterpret_cast<parser_fun_t>(&visitor::visit_semicolonOrCloseTag),
        reinterpret_cast<parser_fun_t>(&visitor::visit_shiftExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_shiftExpressionRest),
        reinterpret_cast<parser_fun_t>(&visitor::visit_start),
        reinterpret_cast<parser_fun_t>(&visitor::visit_statement),
        reinterpret_cast<parser_fun_t>(&visitor::visit_staticArrayPairValue),
        reinterpret_cast<parser_fun_t>(&visitor::visit_staticMember),
        reinterpret_cast<parser_fun_t>(&visitor::visit_staticScalar),
        reinterpret_cast<parser_fun_t>(&visitor::visit_staticVar),
        reinterpret_cast<parser_fun_t>(&visitor::visit_switchCaseList),
        reinterpret_cast<parser_fun_t>(&visitor::visit_topStatement),
        reinterpret_cast<parser_fun_t>(&visitor::visit_unaryExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_unaryExpression_not_plusminus),
        reinterpret_cast<parser_fun_t>(&visitor::visit_varExpression),
        reinterpret_cast<parser_fun_t>(&visitor::visit_varExpressionNewObject),
        reinterpret_cast<parser_fun_t>(&visitor::visit_varExpressionNormal),
        reinterpret_cast<parser_fun_t>(&visitor::visit_variable),
        reinterpret_cast<parser_fun_t>(&visitor::visit_variableName),
        reinterpret_cast<parser_fun_t>(&visitor::visit_variableProperty),
        reinterpret_cast<parser_fun_t>(&visitor::visit_variableWithoutObjects),
        reinterpret_cast<parser_fun_t>(&visitor::visit_whileStatement)
      }; // _S_parser_table[]

} // end of namespace rphp


