#!/usr/bin/php
<?

if ($argc == 0) {
	die("pass script name to tokenize\n");
}
//echo "tokens in: ".$argv[1]."\n";
$tokens = token_get_all(file_get_contents($argv[1]));
foreach ($tokens as $t) {
	if (is_array($t))
		echo str_replace("\n","",$t[1]).' '.token_name($t[0])."\n";
	else
		echo $t.' '.$t."\n";
}

?>